// ── Carehia App Registry ──
// Phase 11 Phase 2: Complete route and action definitions for Carehia.
// No external app modifications. Definitions only.

import {
  KaiRouteRegistryEntry,
  KaiActionRegistryEntry,
  KaiUserRole,
  KaiRouteType,
  KaiNavigationRiskLevel,
} from '../types';

const now = new Date().toISOString();

function route(
  routeKey: string, routeLabel: string, routePath: string,
  routeType: KaiRouteType, allowedRoles: KaiUserRole[],
  riskLevel: KaiNavigationRiskLevel,
  opts?: { requiresConfirmation?: boolean; requiresAdminApproval?: boolean; description?: string },
): KaiRouteRegistryEntry {
  return {
    id: `route_carehia_${routeKey}`, appId: 'carehia', routeKey, routeLabel, routePath, routeType,
    allowedRoles, riskLevel,
    requiresConfirmation: opts?.requiresConfirmation ?? riskLevel === 'medium',
    requiresAdminApproval: opts?.requiresAdminApproval ?? riskLevel === 'high',
    description: opts?.description, isActive: true, createdAt: now, updatedAt: now,
  };
}

function action(
  actionKey: string, actionLabel: string, actionType: string,
  allowedRoles: KaiUserRole[], riskLevel: KaiNavigationRiskLevel,
  opts?: { requiresConfirmation?: boolean; requiresAdminApproval?: boolean; blocked?: boolean; description?: string },
): KaiActionRegistryEntry {
  return {
    id: `action_carehia_${actionKey}`, appId: 'carehia', actionKey, actionLabel, actionType,
    allowedRoles, riskLevel,
    requiresConfirmation: opts?.requiresConfirmation ?? riskLevel === 'medium',
    requiresAdminApproval: opts?.requiresAdminApproval ?? riskLevel === 'high',
    blocked: opts?.blocked ?? riskLevel === 'blocked',
    description: opts?.description, isActive: true, createdAt: now, updatedAt: now,
  };
}

// ── Carehia Routes ──

export const CAREHIA_ROUTES: KaiRouteRegistryEntry[] = [
  // Caregiver-facing
  route('today', 'Today', '/today', 'screen',
    ['caregiver', 'client', 'agency-admin', 'admin', 'super-admin'], 'low',
    { description: 'Daily overview dashboard' }),
  route('work', 'Work', '/work', 'screen',
    ['caregiver', 'agency-admin', 'admin', 'super-admin'], 'low',
    { description: 'Work queue and assignments' }),
  route('schedule', 'Schedule', '/schedule', 'screen',
    ['caregiver', 'client', 'agency-admin', 'admin', 'super-admin'], 'low',
    { description: 'Schedule management' }),
  route('time_tracker', 'Time Tracker', '/time-tracker', 'screen',
    ['caregiver', 'agency-admin', 'admin', 'super-admin'], 'low',
    { description: 'Time tracking and hours log' }),
  route('clients', 'Clients', '/clients', 'screen',
    ['caregiver', 'agency-admin', 'admin', 'super-admin'], 'low',
    { description: 'Client directory' }),
  route('invoices', 'Invoices', '/invoices', 'screen',
    ['caregiver', 'client', 'agency-admin', 'admin', 'super-admin'], 'medium',
    { description: 'Invoice management' }),
  route('trust_passport', 'Trust Passport', '/trust-passport', 'trust_sensitive',
    ['caregiver', 'agency-admin', 'admin', 'super-admin'], 'high',
    { description: 'Identity verification and trust credentials' }),
  route('certifications', 'Certifications', '/certifications', 'trust_sensitive',
    ['caregiver', 'agency-admin', 'admin', 'super-admin'], 'high',
    { description: 'Professional certifications management' }),
  route('reviews', 'Reviews', '/reviews', 'screen',
    ['caregiver', 'client', 'agency-admin', 'admin', 'super-admin'], 'medium',
    { description: 'Reviews and ratings' }),
  route('profile', 'Profile', '/profile', 'screen',
    ['caregiver', 'client', 'agency-admin', 'admin', 'super-admin', 'viewer'], 'low',
    { description: 'User profile settings' }),
  route('support', 'Support', '/support', 'support',
    ['caregiver', 'client', 'agency-admin', 'admin', 'super-admin', 'viewer'], 'low',
    { description: 'Help and support center' }),

  // Client-facing
  route('client_today', 'Client Today', '/client/today', 'screen',
    ['client', 'admin', 'super-admin'], 'low',
    { description: 'Client daily overview' }),
  route('care_team', 'Care Team', '/care-team', 'screen',
    ['client', 'admin', 'super-admin'], 'low',
    { description: 'View assigned care team' }),
  route('schedule_care', 'Schedule Care', '/schedule-care', 'screen',
    ['client', 'admin', 'super-admin'], 'low',
    { description: 'Schedule care sessions' }),
  route('hire_offers', 'Hire Offers', '/hire-offers', 'screen',
    ['client', 'admin', 'super-admin'], 'low',
    { description: 'View and respond to hire offers' }),
  route('caregiver_profiles', 'Caregiver Profiles', '/caregiver-profiles', 'screen',
    ['client', 'admin', 'super-admin'], 'medium',
    { description: 'Browse caregiver profiles' }),

  // Agency/Admin-facing
  route('admin_dashboard', 'Admin Dashboard', '/admin/dashboard', 'admin_panel',
    ['agency-admin', 'admin', 'super-admin'], 'low',
    { description: 'Admin overview dashboard' }),
  route('admin_verification_queue', 'Verification Queue', '/admin/verification-queue', 'admin_panel',
    ['agency-admin', 'admin', 'super-admin'], 'high',
    { description: 'Admin verification review queue' }),
  route('admin_incident_queue', 'Incident Queue', '/admin/incident-queue', 'admin_panel',
    ['agency-admin', 'admin', 'super-admin'], 'high',
    { description: 'Admin incident management' }),
  route('admin_caregivers', 'Admin Caregivers', '/admin/caregivers', 'admin_panel',
    ['agency-admin', 'admin', 'super-admin'], 'medium',
    { description: 'Manage caregivers' }),
  route('admin_clients', 'Admin Clients', '/admin/clients', 'admin_panel',
    ['admin', 'super-admin'], 'medium',
    { description: 'Manage clients' }),
  route('admin_reviews', 'Admin Reviews', '/admin/reviews', 'admin_panel',
    ['admin', 'super-admin'], 'medium',
    { description: 'Review moderation' }),
  route('admin_billing', 'Admin Billing', '/admin/billing', 'payment_sensitive',
    ['admin', 'super-admin'], 'high',
    { description: 'Billing management' }),
  route('admin_audit_logs', 'Admin Audit Logs', '/admin/audit-logs', 'admin_panel',
    ['admin', 'super-admin'], 'high',
    { description: 'System audit logs' }),
  route('admin_support_queue', 'Admin Support Queue', '/admin/support-queue', 'admin_panel',
    ['agency-admin', 'admin', 'super-admin'], 'medium',
    { description: 'Support request queue' }),
];

// ── Carehia Actions ──

export const CAREHIA_ACTIONS: KaiActionRegistryEntry[] = [
  // Low-risk
  action('view_today', 'View Today', 'read',
    ['caregiver', 'client', 'agency-admin', 'admin', 'super-admin'], 'low',
    { description: 'View daily overview' }),
  action('view_schedule', 'View Schedule', 'read',
    ['caregiver', 'client', 'agency-admin', 'admin', 'super-admin'], 'low',
    { description: 'View care schedule' }),
  action('view_clients', 'View Clients', 'read',
    ['caregiver', 'agency-admin', 'admin', 'super-admin'], 'low',
    { description: 'View client directory' }),
  action('view_profile', 'View Profile', 'read',
    ['caregiver', 'client', 'agency-admin', 'admin', 'super-admin', 'viewer'], 'low',
    { description: 'View user profile' }),
  action('view_support', 'View Support', 'read',
    ['caregiver', 'client', 'agency-admin', 'admin', 'super-admin', 'viewer'], 'low',
    { description: 'View support center' }),
  action('draft_support_request', 'Draft Support Request', 'write',
    ['caregiver', 'client', 'agency-admin', 'admin', 'super-admin'], 'low',
    { description: 'Draft a support request for review' }),
  action('summarize_shift_status', 'Summarize Shift Status', 'read',
    ['caregiver', 'agency-admin', 'admin', 'super-admin'], 'low',
    { description: 'Summarize current shift status' }),

  // Medium-risk
  action('edit_profile', 'Edit Profile', 'write',
    ['caregiver', 'client', 'agency-admin', 'admin', 'super-admin'], 'medium',
    { description: 'Edit user profile' }),
  action('update_availability', 'Update Availability', 'write',
    ['caregiver', 'agency-admin', 'admin', 'super-admin'], 'medium',
    { description: 'Update caregiver availability schedule' }),
  action('submit_invoice_draft', 'Submit Invoice Draft', 'write',
    ['caregiver', 'agency-admin', 'admin', 'super-admin'], 'medium',
    { description: 'Submit invoice draft for review' }),
  action('message_client', 'Message Client', 'write',
    ['caregiver', 'agency-admin', 'admin', 'super-admin'], 'medium',
    { description: 'Send message to client' }),
  action('respond_to_review', 'Respond to Review', 'write',
    ['caregiver', 'agency-admin', 'admin', 'super-admin'], 'medium',
    { description: 'Respond to a review' }),
  action('request_document_review', 'Request Document Review', 'write',
    ['caregiver', 'agency-admin', 'admin', 'super-admin'], 'medium',
    { description: 'Request review of uploaded document' }),

  // High-risk
  action('submit_certification_for_review', 'Submit Certification for Review', 'write',
    ['caregiver', 'agency-admin', 'admin', 'super-admin'], 'high',
    { description: 'Submit professional certification for admin review' }),
  action('update_trust_passport_sensitive_info', 'Update Trust Passport Sensitive Info', 'write',
    ['caregiver', 'admin', 'super-admin'], 'high',
    { description: 'Update sensitive identity/trust information' }),
  action('open_admin_verification_review', 'Open Admin Verification Review', 'admin',
    ['agency-admin', 'admin', 'super-admin'], 'high',
    { description: 'Open a verification case for admin review' }),
  action('open_admin_incident_review', 'Open Admin Incident Review', 'admin',
    ['agency-admin', 'admin', 'super-admin'], 'high',
    { description: 'Open an incident case for admin review' }),
  action('change_billing_settings', 'Change Billing Settings', 'admin',
    ['admin', 'super-admin'], 'high',
    { description: 'Change billing configuration' }),

  // Blocked
  action('approve_caregiver_identity', 'Approve Caregiver Identity', 'admin',
    ['super-admin'], 'blocked',
    { description: 'Approve caregiver identity — blocked in Phase 2' }),
  action('approve_background_check', 'Approve Background Check', 'admin',
    ['super-admin'], 'blocked',
    { description: 'Approve background check — blocked in Phase 2' }),
  action('approve_cpr_certification', 'Approve CPR Certification', 'admin',
    ['super-admin'], 'blocked',
    { description: 'Approve CPR certification — blocked in Phase 2' }),
  action('process_payment', 'Process Payment', 'payment',
    ['super-admin'], 'blocked',
    { description: 'Process payment — blocked in Phase 2' }),
  action('issue_refund', 'Issue Refund', 'payment',
    ['super-admin'], 'blocked',
    { description: 'Issue refund — blocked in Phase 2' }),
  action('change_payout_details', 'Change Payout Details', 'payment',
    ['super-admin'], 'blocked',
    { description: 'Change payout details — blocked in Phase 2' }),
  action('grant_admin_access', 'Grant Admin Access', 'admin',
    ['super-admin'], 'blocked',
    { description: 'Grant admin access — blocked in Phase 2' }),
  action('delete_user', 'Delete User', 'admin',
    ['super-admin'], 'blocked',
    { description: 'Delete user — blocked in Phase 2' }),
  action('modify_production_database', 'Modify Production Database', 'admin',
    ['super-admin'], 'blocked',
    { description: 'Modify production database — blocked in Phase 2' }),
];
