// ── Viliniu App Registry ──
// Phase 11 Phase 2: Complete route and action definitions for Viliniu.

import {
  KaiRouteRegistryEntry,
  KaiActionRegistryEntry,
  KaiUserRole,
  KaiRouteType,
  KaiNavigationRiskLevel,
} from '../types';

const now = new Date().toISOString();

function route(
  routeKey: string, routeLabel: string, routePath: string,
  routeType: KaiRouteType, allowedRoles: KaiUserRole[],
  riskLevel: KaiNavigationRiskLevel,
  opts?: { requiresConfirmation?: boolean; requiresAdminApproval?: boolean; description?: string },
): KaiRouteRegistryEntry {
  return {
    id: `route_viliniu_${routeKey}`, appId: 'viliniu', routeKey, routeLabel, routePath, routeType,
    allowedRoles, riskLevel,
    requiresConfirmation: opts?.requiresConfirmation ?? riskLevel === 'medium',
    requiresAdminApproval: opts?.requiresAdminApproval ?? riskLevel === 'high',
    description: opts?.description, isActive: true, createdAt: now, updatedAt: now,
  };
}

function action(
  actionKey: string, actionLabel: string, actionType: string,
  allowedRoles: KaiUserRole[], riskLevel: KaiNavigationRiskLevel,
  opts?: { requiresConfirmation?: boolean; requiresAdminApproval?: boolean; blocked?: boolean; description?: string },
): KaiActionRegistryEntry {
  return {
    id: `action_viliniu_${actionKey}`, appId: 'viliniu', actionKey, actionLabel, actionType,
    allowedRoles, riskLevel,
    requiresConfirmation: opts?.requiresConfirmation ?? riskLevel === 'medium',
    requiresAdminApproval: opts?.requiresAdminApproval ?? riskLevel === 'high',
    blocked: opts?.blocked ?? riskLevel === 'blocked',
    description: opts?.description, isActive: true, createdAt: now, updatedAt: now,
  };
}

// ── Viliniu Routes ──

export const VILINIU_ROUTES: KaiRouteRegistryEntry[] = [
  // Customer-facing
  route('today', 'Today', '/today', 'screen',
    ['customer', 'vendor', 'driver', 'admin', 'super-admin', 'viewer'], 'low',
    { description: 'Daily overview' }),
  route('directory', 'Directory', '/directory', 'screen',
    ['customer', 'vendor', 'admin', 'super-admin', 'viewer'], 'low',
    { description: 'Vendor directory' }),
  route('vendor_store', 'Vendor Store', '/vendor-store', 'screen',
    ['customer', 'vendor', 'admin', 'super-admin', 'viewer'], 'low',
    { description: 'Individual vendor storefront' }),
  route('cart', 'Cart', '/cart', 'screen',
    ['customer', 'admin', 'super-admin'], 'medium',
    { description: 'Shopping cart' }),
  route('checkout', 'Checkout', '/checkout', 'screen',
    ['customer', 'admin', 'super-admin'], 'medium',
    { description: 'Order checkout' }),
  route('orders', 'Orders', '/orders', 'screen',
    ['customer', 'vendor', 'admin', 'super-admin'], 'low',
    { description: 'Order history and tracking' }),
  route('receipts', 'Receipts', '/receipts', 'screen',
    ['customer', 'vendor', 'admin', 'super-admin'], 'low',
    { description: 'Purchase receipts' }),
  route('support', 'Support', '/support', 'support',
    ['customer', 'vendor', 'driver', 'admin', 'super-admin', 'viewer'], 'low',
    { description: 'Help and support center' }),

  // Vendor-facing
  route('vendor_today', 'Vendor Today', '/vendor/today', 'screen',
    ['vendor', 'admin', 'super-admin'], 'low',
    { description: 'Vendor daily overview' }),
  route('vendor_orders', 'Vendor Orders', '/vendor/orders', 'screen',
    ['vendor', 'admin', 'super-admin'], 'low',
    { description: 'Vendor order management' }),
  route('vendor_products', 'Vendor Products', '/vendor/products', 'screen',
    ['vendor', 'admin', 'super-admin'], 'medium',
    { description: 'Product management' }),
  route('vendor_store_profile', 'Vendor Store Profile', '/vendor/store-profile', 'screen',
    ['vendor', 'admin', 'super-admin'], 'medium',
    { description: 'Vendor store profile management' }),
  route('vendor_customers', 'Vendor Customers', '/vendor/customers', 'screen',
    ['vendor', 'admin', 'super-admin'], 'low',
    { description: 'Vendor customer list' }),
  route('vendor_receipts', 'Vendor Receipts', '/vendor/receipts', 'screen',
    ['vendor', 'admin', 'super-admin'], 'low',
    { description: 'Vendor sales receipts' }),
  route('vendor_support', 'Vendor Support', '/vendor/support', 'support',
    ['vendor', 'admin', 'super-admin'], 'low',
    { description: 'Vendor support center' }),
  route('vendor_payouts', 'Vendor Payouts', '/vendor/payouts', 'payment_sensitive',
    ['vendor', 'admin', 'super-admin'], 'high',
    { description: 'Vendor payout management' }),
  route('vendor_settings', 'Vendor Settings', '/vendor/settings', 'settings',
    ['vendor', 'admin', 'super-admin'], 'medium',
    { description: 'Vendor store settings' }),

  // Driver-facing
  route('driver_today', 'Driver Today', '/driver/today', 'screen',
    ['driver', 'admin', 'super-admin'], 'low',
    { description: 'Driver daily overview' }),
  route('delivery_orders', 'Delivery Orders', '/driver/delivery-orders', 'screen',
    ['driver', 'admin', 'super-admin'], 'medium',
    { description: 'Active delivery assignments' }),
  route('delivery_order_detail', 'Delivery Order Detail', '/driver/delivery-orders/:id', 'screen',
    ['driver', 'admin', 'super-admin'], 'medium',
    { description: 'Delivery order details' }),
  route('delivery_proof', 'Delivery Proof', '/driver/delivery-proof', 'proof',
    ['driver', 'admin', 'super-admin'], 'medium',
    { description: 'Delivery proof submission' }),
  route('driver_history', 'Driver History', '/driver/history', 'screen',
    ['driver', 'admin', 'super-admin'], 'low',
    { description: 'Delivery history' }),
  route('driver_support', 'Driver Support', '/driver/support', 'support',
    ['driver', 'admin', 'super-admin'], 'low',
    { description: 'Driver support center' }),

  // Admin-facing
  route('admin_dashboard', 'Admin Dashboard', '/admin/dashboard', 'admin_panel',
    ['admin', 'super-admin'], 'low',
    { description: 'Admin overview dashboard' }),
  route('admin_vendor_review', 'Vendor Review', '/admin/vendor-review', 'admin_panel',
    ['admin', 'super-admin'], 'high',
    { description: 'Admin vendor review queue' }),
  route('admin_orders', 'Admin Orders', '/admin/orders', 'admin_panel',
    ['admin', 'super-admin'], 'medium',
    { description: 'Admin order management' }),
  route('admin_disputes', 'Admin Disputes', '/admin/disputes', 'admin_panel',
    ['admin', 'super-admin'], 'high',
    { description: 'Dispute resolution management' }),
  route('admin_delivery_proof', 'Admin Delivery Proof', '/admin/delivery-proof', 'admin_panel',
    ['admin', 'super-admin'], 'medium',
    { description: 'Delivery proof review' }),
  route('admin_payout_review', 'Admin Payout Review', '/admin/payout-review', 'payment_sensitive',
    ['admin', 'super-admin'], 'high',
    { description: 'Payout review and approval' }),
  route('admin_audit_logs', 'Admin Audit Logs', '/admin/audit-logs', 'admin_panel',
    ['admin', 'super-admin'], 'high',
    { description: 'System audit logs' }),
  route('admin_support_queue', 'Admin Support Queue', '/admin/support-queue', 'admin_panel',
    ['admin', 'super-admin'], 'medium',
    { description: 'Support request queue' }),
];

// ── Viliniu Actions ──

export const VILINIU_ACTIONS: KaiActionRegistryEntry[] = [
  // Low-risk
  action('view_directory', 'View Directory', 'read',
    ['customer', 'vendor', 'admin', 'super-admin', 'viewer'], 'low',
    { description: 'Browse vendor directory' }),
  action('view_order', 'View Order', 'read',
    ['customer', 'vendor', 'driver', 'admin', 'super-admin'], 'low',
    { description: 'View order details' }),
  action('view_receipt', 'View Receipt', 'read',
    ['customer', 'vendor', 'admin', 'super-admin'], 'low',
    { description: 'View purchase receipt' }),
  action('view_delivery_proof', 'View Delivery Proof', 'read',
    ['customer', 'vendor', 'driver', 'admin', 'super-admin'], 'low',
    { description: 'View delivery proof photos' }),
  action('draft_vendor_message', 'Draft Vendor Message', 'write',
    ['customer', 'admin', 'super-admin'], 'low',
    { description: 'Draft a message to a vendor' }),
  action('draft_support_request', 'Draft Support Request', 'write',
    ['customer', 'vendor', 'driver', 'admin', 'super-admin'], 'low',
    { description: 'Draft a support request' }),
  action('summarize_order_status', 'Summarize Order Status', 'read',
    ['customer', 'vendor', 'driver', 'admin', 'super-admin'], 'low',
    { description: 'Summarize order status' }),

  // Medium-risk
  action('update_vendor_profile', 'Update Vendor Profile', 'write',
    ['vendor', 'admin', 'super-admin'], 'medium',
    { description: 'Update vendor store profile' }),
  action('add_product', 'Add Product', 'write',
    ['vendor', 'admin', 'super-admin'], 'medium',
    { description: 'Add new product to store' }),
  action('edit_product', 'Edit Product', 'write',
    ['vendor', 'admin', 'super-admin'], 'medium',
    { description: 'Edit existing product' }),
  action('change_product_price', 'Change Product Price', 'write',
    ['vendor', 'admin', 'super-admin'], 'medium',
    { description: 'Change product pricing' }),
  action('mark_product_out_of_stock', 'Mark Product Out of Stock', 'write',
    ['vendor', 'admin', 'super-admin'], 'medium',
    { description: 'Mark product as out of stock' }),
  action('accept_order', 'Accept Order', 'write',
    ['vendor', 'admin', 'super-admin'], 'medium',
    { description: 'Accept incoming order' }),
  action('assign_delivery_driver', 'Assign Delivery Driver', 'write',
    ['vendor', 'admin', 'super-admin'], 'medium',
    { description: 'Assign a driver for delivery' }),
  action('mark_order_ready', 'Mark Order Ready', 'write',
    ['vendor', 'admin', 'super-admin'], 'medium',
    { description: 'Mark order as ready for pickup' }),
  action('upload_delivery_photo', 'Upload Delivery Photo', 'write',
    ['driver', 'admin', 'super-admin'], 'medium',
    { description: 'Upload delivery proof photo' }),
  action('mark_order_delivered', 'Mark Order Delivered', 'write',
    ['driver', 'admin', 'super-admin'], 'medium',
    { description: 'Mark order as delivered' }),
  action('submit_dispute', 'Submit Dispute', 'write',
    ['customer', 'vendor', 'admin', 'super-admin'], 'medium',
    { description: 'Submit order dispute' }),

  // High-risk
  action('request_payout_change', 'Request Payout Change', 'payment',
    ['vendor', 'admin', 'super-admin'], 'high',
    { description: 'Request change to payout settings' }),
  action('open_payout_settings', 'Open Payout Settings', 'payment',
    ['vendor', 'admin', 'super-admin'], 'high',
    { description: 'Open payout settings page' }),
  action('approve_vendor', 'Approve Vendor', 'admin',
    ['admin', 'super-admin'], 'high',
    { description: 'Approve vendor application' }),
  action('suspend_vendor', 'Suspend Vendor', 'admin',
    ['admin', 'super-admin'], 'high',
    { description: 'Suspend vendor account' }),
  action('approve_refund', 'Approve Refund', 'payment',
    ['admin', 'super-admin'], 'high',
    { description: 'Approve customer refund' }),
  action('override_order_status', 'Override Order Status', 'admin',
    ['admin', 'super-admin'], 'high',
    { description: 'Override order status manually' }),
  action('review_dispute', 'Review Dispute', 'admin',
    ['admin', 'super-admin'], 'high',
    { description: 'Review and resolve dispute' }),

  // Blocked
  action('process_payout', 'Process Payout', 'payment',
    ['super-admin'], 'blocked',
    { description: 'Process vendor payout — blocked in Phase 2' }),
  action('change_bank_details', 'Change Bank Details', 'payment',
    ['super-admin'], 'blocked',
    { description: 'Change bank details — blocked in Phase 2' }),
  action('change_mpaisa_details', 'Change M-Paisa Details', 'payment',
    ['super-admin'], 'blocked',
    { description: 'Change M-Paisa details — blocked in Phase 2' }),
  action('issue_refund_automatically', 'Issue Refund Automatically', 'payment',
    ['super-admin'], 'blocked',
    { description: 'Auto-issue refund — blocked in Phase 2' }),
  action('delete_vendor', 'Delete Vendor', 'admin',
    ['super-admin'], 'blocked',
    { description: 'Delete vendor — blocked in Phase 2' }),
  action('delete_customer', 'Delete Customer', 'admin',
    ['super-admin'], 'blocked',
    { description: 'Delete customer — blocked in Phase 2' }),
  action('grant_admin_access', 'Grant Admin Access', 'admin',
    ['super-admin'], 'blocked',
    { description: 'Grant admin access — blocked in Phase 2' }),
  action('modify_production_database', 'Modify Production Database', 'admin',
    ['super-admin'], 'blocked',
    { description: 'Modify production database — blocked in Phase 2' }),
  action('approve_vendor_automatically', 'Approve Vendor Automatically', 'admin',
    ['super-admin'], 'blocked',
    { description: 'Auto-approve vendor — blocked in Phase 2' }),
];
